[workspace]
members = [
    "src-tauri",
]
default-members = ["src-tauri"]
resolver = "2"

[profile.release]
opt-level = "z"      # サイズ最優先の最適化
lto = true           # Link-Time Optimization の有効化
codegen-units = 1    # コードジェネレータのユニット数を1にして最適化を保護
panic = "abort"      # パニック時の巻き戻しコードを除外してサイズ削減
strip = true         # デバッグシンボルとシンボルテーブルの自動削除
